name: Legends_Reborn
version: '1.1'
main: pine.toast.legendsreborn.EternalRealms_LegendsReborn
api-version: '1.20'
depend:
  - mana
  - Overhaul-Systems

commands:
  
  togglesubscription:
    description: Gives a subscription to a player
    usage: /<command> [Optional <Player>]
  
  whoami:
    description: Shows you your class
    usage: /<command>
  
  togglexp:
    description: Toggles your exp action bar
    usage: /<command>
  
  tteam:
    description: Manage teams
    usage: /tteam <create|join|leave|info>
  
  pay:
    description: Pay command
    usage: /pay <player> <amount>
  
  auctionhouse:
    aliases: ah
    description: Open the auction house
    usage: /ah OR /auctionhouse
